name: Check Wordle Word List

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: maciej-irl/wate
          lfs: false

      - name: Run the Scraper
        run: |
          pip install requests
          python scrape_word_list.py
